### ISSUE TITLE
Add eventhandlers

### ISSUE THREAD

**Issue by SilverGeri** [VSZM/Dixit_By_MonkeyzWithKeyboardz_ELTE#17]
Provide necessary eventhandlers for dixit_client
Currently these are:
- When login fails, we need an eventhandler that carries the information why it failed
- When login is successful, we need an eventhandler that carries the initial gamestate

**Comment by selleim** [comment]
A Service.Login() exception-t fog dobni, abban az esetben, hogy ha nem sikerült a login.
Ez az exception tartalmazni fogja a hibaüzenet, amit a model-ből már lehet majd továbbítani event formájában.
Service.JoinGame() visszadja majd a gamestate-et, login-t hagyjuk meg csak az authentikációnak.

**Comment by selleim** [comment]
Ha megcsinálhatom a kliens.model-ben a service kommunikációt akkor onnan már küldhetek event-eket.

**Comment by VSZM** [comment]
Csináld nyugodtan.
