### ISSUE TITLE
Create methods in model

### ISSUE THREAD

**Issue by SilverGeri** [VSZM/Dixit_By_MonkeyzWithKeyboardz_ELTE#59]
<del>In Dixit_Client's Model a method is needed to communicate the selected card to the service.</del>
Also, another event is needed to get who selected which card (maybe just modify `GuessPhaseEndEvent` to have `GameStateEventArgs` parameter)

Also, the service's `JoinGame` function should invoke a callback about a player joining a game because we have a list on the clientside where we would like to list the joined players (on the loginwindow)

**Comment by VSZM** [comment]
@SilverGeri IDixitService.NewGuess(Card card); does the first.
Also IDixitServiceCallback.GameStateChanged(GameState state); will signal the clients if there is a gamestate change. GameState object contains the 2nd information you seek: Guesses dictionary.
On the client side you just have to register for this callback and store the info.

**Comment by SilverGeri** [comment]
@VSZM first one is OK, found it. But GuessPhaseEnd doesn't have the necessary parameter. On a GameStateChangedEvent, I don't know if everyone finished guessing or not. I don't store the gamestate on the clientside, it would make no sense from the project structure.

**Comment by VSZM** [comment]
Ah, ok. Makes sense
