### ISSUE TITLE
Design persistence layer - Brigi

### ISSUE THREAD

**Issue by VSZM** [VSZM/Dixit_By_MonkeyzWithKeyboardz_ELTE#6]
How to store and load cards?

**Comment by ballaibrigitt42** [comment]
Lenne egy adatbázis, ahol a kártyákhoz a path-ot tárolnánk. Elkészítettem az interfészt egy függvénnyel. A játék során csak olyan műveletre lesz szükségünk, ami betölti a kártyákat. Utánanéztem, hogy hogyan lehet VS-ben létrehozni adatbázist/táblát/oszlopokat/sorokat.

**Comment by VSZM** [comment]
Please add the following methods to the interface:
- Get the list of card ids from the database
- Get the Image associated to a card id

Take a look at how Marci and Matyi designed the ICard class.
Also think of a way on how to store these images.

**Comment by SilverGeri** [comment]
It blocks us, as we can not use anything in the view
